anisite/config/routes.rb
Rails.application.routes.draw do
  resources :animes
  
  resources :users do
    resources :comments
  end
  
  root 'home#default'
  
  get 'about' => 'about#default'
  
  get 'contact' => 'contact#default'
  
  get 'login' => 'logins#new'
  
  post 'login' => 'logins#create'
  
  get 'logout' => 'logins#destroy'
  

end

anisite/app/models/anime.rb
class Anime < ActiveRecord::Base
  
  validates :title, presence:true, uniqueness:true
  
  has_many :observations
  has_many :users, through: :observations
  
  def self.get_reviews(anime)
    return anime.observations.joins(:user).select(:username,:review).where.not(review:"")
  end
  
end

anisite/app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :user

end

anisite/app/models/observation.rb
class Observation < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :anime

end

anisite/app/models/user.rb
class User < ActiveRecord::Base
  
  validates :email, presence:true
  validates :username, presence:true, uniqueness:true
  validates :password, length: { in: 8..72 }
  
  has_many :observations
  has_many :animes, through: :observations
  has_many :comments
  
  has_secure_password
end

anisite/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def default
  end
end

anisite/app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:show, :edit, :update, :destroy]

  # GET /animes
  # GET /animes.json
  def index
    @animes = Anime.all
  end

  # GET /animes/1
  # GET /animes/1.json
  def show
    
    @reviews = Anime.get_reviews(@anime)

  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes
  # POST /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: 'Anime was successfully created.' }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1
  # PATCH/PUT /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: 'Anime was successfully updated.' }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1
  # DELETE /animes/1.json
  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: 'Anime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anime_params
      params.require(:anime).permit(:title, :year, :number_of_episodes, :description)
    end
end

anisite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include LoginsHelper
end

anisite/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
  end
  
  def create
    @user = User.find(params[:user_id])
    cp = comment_params
    cp[:receiver_id] = (current_user).id
    @comment = @user.comments.create(cp)
    redirect_to user_path(@user)
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:written_comment)
  end
  
end

anisite/app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def default
  end
end

anisite/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def default
  end
end

anisite/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email:params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
  
end

anisite/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @animesseen = @user.animes
    @comments = @user.comments.joins('INNER JOIN users ON users.id = comments.receiver_id').select(:username,:written_comment).paginate(:page => params[:page], :per_page => 2)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
    if (current_user).id != @user.id
      render :status => :forbidden, :text => "Forbidden"
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :surname, :email, :password, :password_confirmation, :username)
    end
end

anisite/app/helpers/about_helper.rb
module AboutHelper
end

anisite/app/helpers/animes_helper.rb
module AnimesHelper
end

anisite/app/helpers/application_helper.rb
module ApplicationHelper
end

anisite/app/helpers/comments_helper.rb
module CommentsHelper
end

anisite/app/helpers/contact_helper.rb
module ContactHelper
end

anisite/app/helpers/home_helper.rb
module HomeHelper
end

anisite/app/helpers/logins_helper.rb
module LoginsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

anisite/app/helpers/users_helper.rb
module UsersHelper
end

anisite/app/views/about/default.html.erb
<% provide(:title, 'Anisite | About') %>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>About</h1>
		<p>
			This site was designed in order to act as a vehicle through which it would be possible to learn the programming language Ruby, and the
			associated web development framework Ruby on Rails.
		</p>
	</div>
</div>

anisite/app/views/animes/_edit_form.html.erb
<%= form_for(@anime) do |f| %>
<% if @anime.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

	<ul>
		<% @anime.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :title %><br>
	<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="field">
	<%= f.label :year %><br>
	<%= f.number_field :year, class: 'form-control' %>
</div>
<div class="field">
	<%= f.label :number_of_episodes %><br>
	<%= f.number_field :number_of_episodes, class: 'form-control' %>
</div>
<div class="field">
	<%= f.label :description %><br>
	<%= f.text_area :description, class: 'form-control' %>
</div>
<div class="actions">
	<%= f.submit "Update anime", class: "btn btn-primary" %>
</div>
<% end %>

anisite/app/views/animes/_form.html.erb
<%= form_for(@anime) do |f| %>
<% if @anime.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

	<ul>
		<% @anime.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :year %><br>
	<%= f.number_field :year %>
</div>
<div class="field">
	<%= f.label :number_of_episodes %><br>
	<%= f.number_field :number_of_episodes %>
</div>
<div class="field">
	<%= f.label :description %><br>
	<%= f.text_area :description %>
</div>
<div class="actions">
	<%= f.submit "Create Account", class: "btn btn-primary" %>
</div>
<% end %>

anisite/app/views/animes/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>Editing Anime</h1>

		<%= render 'edit_form' %>

		<%= link_to "Back to #{@anime.title}", @anime %>

	</div>
</div>

anisite/app/views/animes/index.html.erb
<% provide(:title, "Anisite | Anime") %>
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Anime</h1>
		<table>
			<thead>
				<tr>
					<th>Title</th>
					<th>Year</th>
					<th>Number of episodes</th>
					<th>Number of users who have watched this anime</th>
					<th>Average rating out of 10</th>
				</tr>
			</thead>

			<tbody>
				<% @animes.each do |anime| %>
				<tr>
					<td><%= anime.title %></td>
					<td><%= anime.year %></td>
					<td><%= anime.number_of_episodes %></td>
					<td><%= anime.observations.count %></td>
					<td><%= anime.observations.average(:rating) %></td>
					<td><%= link_to 'View anime profile', anime %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<br>

		<%= link_to 'New Anime', new_anime_path %>
	</div>
</div>

anisite/app/views/animes/new.html.erb
<% provide(:title, "Add anime") %>
<div class="row">
	<div class="col-md-4  col-md-offset-4">
<h1>New Anime</h1>
<%= render 'form' %>
<%= link_to 'Back to anime list', animes_path %>
</div>
</div>

anisite/app/views/animes/show.html.erb
<% provide(:title, "Anisite | #{@anime.title}") %>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<p id="notice"><%= notice %></p>

		<h1><%= "#{@anime.title}" + (@anime.year.nil? ? "" : " (#{@anime.year})") %></h1>
		
		<h3><%= @anime.number_of_episodes.nil? ? "" : "#{@anime.number_of_episodes} episode(s)"%></h3>

		<p>
			<%= @anime.description %>
		</p>
		
		<h3>Reviews</h3>
		<% @reviews.each do |review| %>
		<p><%= "#{review.username} - #{review.review}"  %></p>
		<% end %>

		<%= link_to 'Edit', edit_anime_path(@anime) %> |
		<%= link_to 'Destroy', :anime, method: :delete, data: { confirm: 'Are you sure?' } %> |
		<%= link_to 'Back to anime list', animes_path %>
	</div>
</div>

anisite/app/views/contact/default.html.erb
<% provide(:title, 'Anisite | Contact') %>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>Contact</h1>
		<p>
			The site author can be contacted by sending an email to the following address: anisite_author@outlook.com.
		</p>
	</div>
</div>

anisite/app/views/home/default.html.erb
<% provide(:title, 'Anisite | Home') %>
<p id="notice"><%= notice %></p>
<div class="container">

     <!-- Main component for a primary marketing message or call to action -->
     <div class="jumbotron">
       <h1>Navbar example</h1>
       <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
       <p>To see the difference between static and fixed top navbars, just scroll.</p>
       <p>
         <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
       </p>
     </div>

   </div>

anisite/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">AniSite</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Anime", animes_path %></li>
				<li><%= link_to "Members", users_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<% if logged_in? %>
						<li><%= link_to "My Account", current_user %></li>
						<li><%= link_to "Log Out", logout_path %></li>
						<% else %>
						<li><%= link_to "Sign Up", new_user_path %></li>
						<li><%= link_to "Log In", login_path %></li>
						<% end %>
					</ul>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>

anisite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/navbar" %>
	

	<%= yield %>

</body>
</html>

anisite/app/views/logins/new.html.erb
<% provide(:title, 'Anisite | Log In') %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
	<% if flash[:danger] %>
	    <div class="dange"><%= flash[:danger] %></div>
	  <% end %>
	<h1>Log In</h1>
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

anisite/app/views/users/_edit_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, :placeholder => "Please enter your first name...", class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname, :placeholder => "Please enter your surname...", class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :placeholder => "Please enter your email address...", class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :placeholder => "Please enter your desired password...", class: 'form-control' %>
  </div>
<div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, :placeholder => "Please confirm your desired password...", class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Update Account", class: "btn btn-primary" %>
  </div>
<% end %>

anisite/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, :placeholder => "Please enter your first name...", class: 'form-control' %>

    <%= f.label :surname %><br>
    <%= f.text_field :surname, :placeholder => "Please enter your surname...", class: 'form-control' %>

    <%= f.label :email %><br>
    <%= f.text_field :email, :placeholder => "Please enter your email address...", class: 'form-control' %>

	<%= f.label :username %>
	<%= f.text_field :username, :placeholder => "Please enter your desired username...", class: 'form-control' %>

    <%= f.label :password %><br>
    <%= f.password_field :password, :placeholder => "Please enter your desired password...", class: 'form-control' %>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, :placeholder => "Please confirm your desired password...", class: 'form-control' %>

    <%= f.submit "Create Account", class: "btn btn-primary" %>
  </div>
<% end %>

anisite/app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>Edit Profile</h1>
		<%= render 'edit_form' %>

		<%= link_to 'Back to my profile', @user %>
	</div>
</div>

anisite/app/views/users/index.html.erb
<% provide(:title, "Anisite | Members") %>
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Members</h1>

		<table>
			<thead>
				<tr>
					<th>Username</th>
					<th>Animes Seen</th>
					<th>Average rating given by user</th>
				</tr>
			</thead>

			<tbody>
				<% @users.order('first_name ASC').each do |user| %>
				<tr>
					<td><%= user.username %></td>
					<td><%= user.observations.count %></td>
					<td><%= user.observations.average(:rating) %></td>
					<td><%= link_to 'View user profile', user %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<br>
		
		
	</div>
</div>

anisite/app/views/users/new.html.erb
<% provide(:title, 'Anisite | Sign Up') %>
<div class="row">
	<div class="col-md-4  col-md-offset-4">
		<h1>New User</h1>


<%= render 'form' %>



	</div>
</div>

anisite/app/views/users/show.html.erb
<% provide(:title, "Anisite | #{@user.first_name}") %>
<div class="row">
	<div class="col-md-2 col-md-offset-2">
		<p id="notice"><%= notice %></p>
		<p>
			<strong>First name:</strong>
			<%= @user.first_name %>
		</p>

		<p>
			<strong>Surname:</strong>
			<%= @user.surname %>
		</p>

		<p>
			<strong>Email:</strong>
			<%= @user.email %>
		</p>
		<% if @user.id == session[:user_id] %>
		<%= link_to 'Edit', edit_user_path(@user) %> |
		<% end %>
		<%= link_to 'Back to member list', users_path %>
	</div>
	<% if @animesseen.length > 0 %>
	<div id="a", class="col-md-6">
		<% @animesseen.each do |a| %>
		<div class="col-md-4">
			<div class="anime">
				<%= link_to a.title, a %>
			</div>
		</div>
		<% end %>
	</div>
	<% end %>
	
	<% if @comments.length > 0 %>
	<div id="b", class="col-md-6 col-md-offset-4">
		<h3>Comments</h3>
		<% @comments.each do |comment| %>
		<div class="col-md-12">
			<div class="comments">
				<%= "#{comment.username} - #{comment.written_comment}" %>
			</div>
		</div>
		<% end %>
		<%= will_paginate  @comments %>
	</div>
	<% end %>
	<div class="col-md-6 col-md-offset-4">
	<%= form_for([@user, @user.comments.build]) do |f| %>
	  <p>
	    <%= f.label :Write_comment %><br>
	    <%= f.text_area :written_comment %>
	  </p>
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>
	</div>
	
	
</div>